# Generated by Django 3.1.1 on 2020-09-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='classfied',
            new_name='classified',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='upload_date',
            new_name='uploaded',
        ),
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(upload_to='article_images'),
        ),
    ]
